"""Keep the GEMINI tests away from the banked provenance summaries.

``scripts/gemini/out/extraction_summary.json`` and its finalize twin are
tracked in git. They hold the real full-scale extraction's counts, they
can only be regenerated by a multi-hour run on the GEMINI node, and that
node is the only place the source data exists.

Any test that reaches ``run_extraction`` or ``run_finalize`` used to
overwrite them with its own smoke-scale numbers. Because those counts
are suppressed to ``"<6"`` and ``"0"``, the clobbered file still reads
as a valid summary -- one saying GEMINI has almost no data. That
happened on 2026-09-10: 1,118,000 subjects became ``"<6"``, and it was
caught by a file mtime, not by a failing test.

These tests load the scripts fresh from their file path in each test, so
patching a module attribute does not reach them. ``GEMINI_OUT_DIR`` is
read when the module loads, which is inside the test, so setting it here
does.
"""

import pytest


@pytest.fixture(autouse=True)
def _redirect_gemini_out_dir(
    tmp_path_factory: pytest.TempPathFactory, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("GEMINI_OUT_DIR", str(tmp_path_factory.mktemp("gemini_out")))
