"""Emit the two-sided steering table: specificity per dial, against a control.

Reads a steering JSON written with readout shifts and the state-transition
probes (``odyssey.inference.steering --outcome-probes``) and, optionally,
the matching random-direction control, scores every dial with
:mod:`odyssey.inference.specificity`, and writes one LaTeX ``tabular`` with a
row per dial and direction and a totals block per run.

    uv run python scripts/make_specificity_table.py \
        --dials .../full_run_DEC_v12/steering_twosided.json \
        --control .../full_run_DEC_v12/steering_twosided_control_random.json \
        --output-tex paper/ml4h/tables/specificity_mimic.tex
"""

from __future__ import annotations

import argparse
import json
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from odyssey.inference.specificity import (
    DialSpecificity,
    RunTotals,
    score_run,
    totals,
)


DISPLAY_NAMES = {
    "sustained_hypotension_map": "sust.\\ hypotension (MAP)",
    "elevated_lactate": "elevated lactate",
    "metabolic_acidosis": "metabolic acidosis",
    "aki_stage_3": "AKI stage 3",
    "sepsis3": "Sepsis-3",
    "qsofa": "qSOFA",
    "anemia": "severe anemia",
}
ARROW = {"amplify": "$\\uparrow$", "suppress": "$\\downarrow$"}


def _display(concept: str) -> str:
    return DISPLAY_NAMES.get(concept, concept.replace("_", " "))


def _frac(hit: int, of: int) -> str:
    return "--" if of == 0 else f"{hit}/{of}"


def dial_row(d: DialSpecificity) -> str:
    """One LaTeX row: dial, own shift, focus, opposites, collateral, good, bad."""
    return (
        " & ".join(
            [
                f"{_display(d.concept)} {ARROW[d.direction]}",
                f"{d.own_shift:+.2f}",
                f"{d.focus:.2f}",
                _frac(d.opposite_as_expected, d.opposite_declared),
                _frac(d.others_separated, d.others_total),
                _frac(d.good_as_expected, d.good_declared),
                _frac(d.bad_as_expected, d.bad_declared),
            ]
        )
        + " \\\\"
    )


def totals_row(label: str, t: RunTotals) -> str:
    """Render the totals line for one run."""
    return (
        " & ".join(
            [
                f"\\emph{{{label}}} ({t.n_dials} dials)",
                "",
                f"{t.median_focus:.2f}",
                _frac(t.opposite_as_expected, t.opposite_declared),
                "",
                _frac(t.good_as_expected, t.good_declared),
                _frac(t.bad_as_expected, t.bad_declared)
                + f" ({t.both_sided} both-sided)",
            ]
        )
        + " \\\\"
    )


HEADER = (
    "Dial & $\\Delta$ own readout & focus & opposites $\\downarrow$ & "
    "collateral & good outcomes & bad outcomes \\\\"
)


def render(
    dials: Sequence[DialSpecificity],
    control: Sequence[DialSpecificity] | None,
    *,
    source: str,
    control_source: str | None,
) -> str:
    """Render the complete tabular for one database."""
    lines = [
        "% GENERATED by scripts/make_specificity_table.py -- do not hand-edit.",
        f"% source: {source}",
        f"% control: {control_source}",
        "% focus: |own readout shift| / sum of |shift| over every concept;",
        "% opposites: declared physiological opposites whose readout moved down;",
        "% collateral: undeclared readouts whose paired interval excludes zero;",
        "% good/bad outcomes: 24 h declared pairs that moved the declared way",
        "% (good = ICU discharge, discharge alive, vasopressor stop; declared DOWN",
        "% for a sicker state).",
        "\\begin{tabular}{lrrrrrr}",
        "\\toprule",
        HEADER,
        "\\midrule",
    ]
    lines.extend(dial_row(d) for d in dials)
    lines.append("\\midrule")
    lines.append(totals_row("concept dials", totals(dials)))
    if control is not None:
        lines.append(totals_row("random direction", totals(control)))
    lines.extend(["\\bottomrule", "\\end{tabular}"])
    return "\n".join(lines) + "\n"


def _load(path: Path) -> list[dict[str, Any]]:
    return list(json.loads(path.read_text())["summaries"])


def main(argv: Sequence[str] | None = None) -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dials", required=True, type=Path)
    parser.add_argument("--control", type=Path, default=None)
    parser.add_argument("--horizon", type=float, default=24.0)
    parser.add_argument("--output-tex", required=True, type=Path)
    args = parser.parse_args(argv)
    dials = score_run(_load(args.dials), horizon_hours=args.horizon)
    control = (
        score_run(_load(args.control), horizon_hours=args.horizon)
        if args.control is not None
        else None
    )
    tex = render(
        dials,
        control,
        source=str(args.dials),
        control_source=None if args.control is None else str(args.control),
    )
    args.output_tex.parent.mkdir(parents=True, exist_ok=True)
    args.output_tex.write_text(tex)
    t = totals(dials)
    print(
        f"wrote {args.output_tex}: {t.n_dials} dials, median focus {t.median_focus:.2f}, "
        f"opposites {t.opposite_as_expected}/{t.opposite_declared}, "
        f"good {t.good_as_expected}/{t.good_declared}, "
        f"bad {t.bad_as_expected}/{t.bad_declared}, both-sided {t.both_sided}"
    )


if __name__ == "__main__":
    main()
