"""Render the GBM feature-group ablation as a LaTeX table for the paper.

Reads the JSON written by scripts/gbm_feature_ablation.py for one or more
runs and writes one row per (database, event, horizon): the hazard head's
AUROC, the refit GBM's, and the share of the GBM-minus-hazard gap each
feature group explains uniquely (AUROC lost when the group is dropped,
over the gap). Shares above 1 mean the GBM without that group falls below
the hazard head; cells where the head already wins show the gap only.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


GROUPS = (
    ("counts_occurrence", "counts"),
    ("summary_stats", "windows"),
    ("latest_value", "latest"),
    ("recency", "recency"),
    ("static", "static"),
)
EVENT_LABELS = {
    "acute_kidney_injury": "AKI",
    "death": "Death",
    "icu_admission": "ICU adm.",
    "sepsis3": "Sepsis-3",
    "vasopressor_start": "Vasopressor",
}


def _share(cell: dict[str, Any], group: str) -> str:
    v = cell["variants"].get(f"drop:{group}")
    if v is None or v.get("gap_share") is None:
        return "--"
    s = v["gap_share"]
    text = f"{s:.2f}"
    return f"\\textbf{{{text}}}" if s >= 0.5 else text


def render(inputs: list[tuple[str, Path]], *, skip: set[tuple[str, str]]) -> str:
    """Return the LaTeX tabular for the (label, ablation json) inputs, minus skipped cells."""
    lines = [
        "% GENERATED by scripts/make_ablation_table.py -- do not hand-edit.",
        "% unique share = (full GBM AUROC - AUROC with the group dropped) / (full GBM AUROC - hazard AUROC);",
        "% bold >= 0.5; > 1 means the GBM without the group falls below the hazard head.",
        "\\begin{tabular}{llrrrrrrrr}",
        "\\toprule",
        " & Event & $h$ & Hazard & GBM & "
        + " & ".join(label for _, label in GROUPS)
        + " \\\\",
        "\\midrule",
    ]
    for db, path in inputs:
        data = json.loads(path.read_text())
        cells = [c for c in data["cells"] if (db, c["event"]) not in skip]
        first = True
        for c in sorted(cells, key=lambda c: (c["event"], c["horizon_hours"])):
            gap = c["full_auroc"] - c["hazard_auroc"]
            if gap <= 0:
                shares = ["head wins"] + ["" for _ in GROUPS[1:]]
            else:
                shares = [_share(c, g) for g, _ in GROUPS]
            lines.append(
                " & ".join(
                    [
                        db if first else "",
                        EVENT_LABELS.get(c["event"], c["event"]),
                        f"{c['horizon_hours']:g}h",
                        f"{c['hazard_auroc']:.3f}",
                        f"{c['full_auroc']:.3f}",
                        *shares,
                    ]
                )
                + " \\\\"
            )
            first = False
        lines.append("\\midrule")
    lines[-1] = "\\bottomrule"
    lines.append("\\end{tabular}")
    return "\n".join(lines) + "\n"


def main() -> None:
    """Write the table from one or more ablation JSONs."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input", action="append", nargs=2, metavar=("LABEL", "JSON"), required=True
    )
    parser.add_argument(
        "--skip", action="append", nargs=2, metavar=("LABEL", "EVENT"), default=[]
    )
    parser.add_argument("--output-tex", type=Path, required=True)
    args = parser.parse_args()
    text = render(
        [(lab, Path(p)) for lab, p in args.input],
        skip={(lab, e) for lab, e in args.skip},
    )
    args.output_tex.write_text(text)
    print("wrote", args.output_tex)


if __name__ == "__main__":
    main()
