"""Turn the banked intervention CI files into the paper's lever table.

One row per arm; the columns are the paired subject-clustered deltas
(2,000 resamples) the text of Section 5.3 used to carry inline: banded
truth-minus-flip, banded truth-minus-none, and output-calibrated
truth-minus-flip, in top-1 percentage points, plus the loss change under
a true override from the same arm's full-split intervention pass. A
row whose arm has no CI file (the subset-scale independent arms) shows
point values only and says so.

Usage::

    uv run python scripts/make_lever_table.py \\
        --figure-data research_journal/figure_data \\
        --output-tex paper/ml4h/tables/lever_cis.tex
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path
from typing import Any


logger = logging.getLogger(__name__)

# (label, figure_data arm directory); order follows the paper's arms list.
ARMS: tuple[tuple[str, str], ...] = (
    ("Joint mixture, MIMIC-IV", "vm1/full_run_v10"),
    ("Joint mixture, eICU", "vm2/eicu_full_v10"),
    ("Independent mixture, MIMIC-IV", "vm1/subset_run_indep_b"),
    ("Independent mixture, eICU", "vm2/eicu_subset_indep_b"),
    ("Global-poles mixture, MIMIC-IV", "vm1/full_run_L_v10"),
    ("Global-poles mixture, eICU", "vm2/eicu_full_L_v10"),
    ("Additive, eICU", "vm2/eicu_full_ADD_v10"),
    ("Decomposed, MIMIC-IV", "vm1/full_run_DEC_v12"),
    ("Decomposed, eICU", "vm2/eicu_full_DEC_v12"),
    ("Decomposed + steering training, eICU", "vm2/eicu_full_DEC_v12_steer"),
)
PAIRS: tuple[tuple[str, str], ...] = (
    ("truth$-$flip", "truth_minus_flip"),
    ("truth$-$none", "truth_minus_none"),
    ("calibrated truth$-$flip", "truth_calibrated_minus_flip_calibrated"),
)


def _load(path: Path) -> Any:
    with path.open() as f:
        return json.load(f)


def _fmt(pair: dict[str, Any] | None) -> str:
    if pair is None:
        return "--"
    text = f"${100 * pair['point']:+.2f}$ [{100 * pair['ci_low']:+.2f},{100 * pair['ci_high']:+.2f}]"
    return f"\\textbf{{{text}}}" if pair.get("separated") else text


def _point_deltas(modes: dict[str, dict[str, Any]]) -> dict[str, str]:
    """Point-only top-1 deltas from a band15 file, for arms without CIs."""
    none = modes["none"]["top1_accuracy"]
    out = {}
    if "truth" in modes and "flip" in modes:
        out["truth_minus_flip"] = (
            f"${100 * (modes['truth']['top1_accuracy'] - modes['flip']['top1_accuracy']):+.2f}$"
        )
        out["truth_minus_none"] = (
            f"${100 * (modes['truth']['top1_accuracy'] - none):+.2f}$"
        )
    if "truth_calibrated" in modes and "flip_calibrated" in modes:
        out["truth_calibrated_minus_flip_calibrated"] = (
            f"${100 * (modes['truth_calibrated']['top1_accuracy'] - modes['flip_calibrated']['top1_accuracy']):+.2f}$"
        )
    return out


def render(figure_data: Path, arms: tuple[tuple[str, str], ...] = ARMS) -> str:
    """Render the tabular body; arms with no banked files are skipped."""
    lines = [
        "% GENERATED by scripts/make_lever_table.py -- do not hand-edit.",
        "% top-1 percentage points; bold = paired subject-clustered 95% CI excludes 0;",
        "% rows without intervals are point values from the full-split pass (no CI file).",
        "\\begin{tabular}{l" + "r" * len(PAIRS) + "r}",
        "\\toprule",
        "Arm & "
        + " & ".join(label for label, _ in PAIRS)
        + " & $\\Delta$loss (truth) \\\\",
        "\\midrule",
    ]
    for arm_label, arm in arms:
        label = arm_label
        cis = figure_data / arm / "intervention_cis.json"
        band = figure_data / arm / "interventions_band15.json"
        if not band.exists() and not cis.exists():
            logger.info("skipping %s: nothing banked under %s", label, arm)
            continue
        cells = []
        if cis.exists():
            pairs = _load(cis)["pairs"]
            cells = [_fmt(pairs.get(key)) for _, key in PAIRS]
        else:
            modes = {m["mode"]: m for m in _load(band)}
            points = _point_deltas(modes)
            cells = [points.get(key, "--") for _, key in PAIRS]
            label = label + "$^\\ast$"
        loss = "--"
        if band.exists():
            modes = {m["mode"]: m for m in _load(band)}
            if (
                "truth" in modes
                and "none" in modes
                and modes["truth"].get("mean_task_loss") is not None
            ):
                loss = f"${modes['truth']['mean_task_loss'] - modes['none']['mean_task_loss']:+.3f}$"
        lines.append(" & ".join([label, *cells, loss]) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def main() -> None:
    """Write the lever table."""
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--figure-data", type=Path, default=Path("research_journal/figure_data")
    )
    parser.add_argument("--output-tex", type=Path, required=True)
    args = parser.parse_args()
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s"
    )
    args.output_tex.parent.mkdir(parents=True, exist_ok=True)
    args.output_tex.write_text(render(args.figure_data))
    logger.info("wrote %s", args.output_tex)


if __name__ == "__main__":
    main()
