"""Render the input-level counterfactual edits as a LaTeX table with intervals.

paper/ml4h/tables/counterfactual.tex was previously hand-transcribed from
counterfactual.json despite carrying a "do not hand-edit" header, and it
reported bare percentages. Both are fixed here: every number is derived
from the JSON, and every cell carries a Wilson 95% interval.

The intervals matter more for this table than for any other in the paper.
Its arms are the smallest in the manuscript (40 and 44 edited subjects
against the comparator tables' hundreds of thousands of rows), it is the
source of the abstract's "85 to 98%", and the claim it supports is a
separation: the real edits against the inert control, which resets blood
pressure to its own normal value and should sit at chance. A separation
argued from four bare percentages at n=44 is not an argument; with
intervals it either holds or it does not.

Each (edit, event, horizon) cell is one binomial over edited subjects, so
Wilson applies directly. An interval on the 8/24/72 h average would need
the per-subject agreements, which counterfactual.json does not retain
(its ``per_subject`` lists are empty), the same limitation
scripts/make_edit_attribution_ci_table.py documents.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from scripts.make_edit_attribution_ci_table import wilson_interval


HORIZONS = ("8h", "24h", "72h")
EVENT_LABELS = {
    "death": "Death",
    "vasopressor_start": "Vasopressor",
    "icu_admission": "ICU adm.",
    "acute_kidney_injury": "AKI",
}
# Curated prose per arm: the display name and what the edit did. The
# expected DIRECTION is not curated, it is read out of the JSON's own
# expected_direction so the table cannot disagree with what was scored.
ARMS: dict[str, tuple[str, str]] = {
    "hypotension_6h": ("Induced hypotension", "SBP set to 80 mmHg over 6 h"),
    "normotension_6h": (
        "Inert control",
        "SBP set to its own normal value over 6 h",
    ),
    "creatinine_plus_1": ("Creatinine rise", "creatinine $+1$ mg/dL"),
    "lactate_x3": ("Lactate rise", "lactate $\\times 3$"),
}


def _expected(arm: dict[str, Any]) -> dict[str, int]:
    """Merge the expected_direction of every edit spec in one arm."""
    merged: dict[str, int] = {}
    for spec in arm.get("edits", []):
        merged.update(spec.get("expected_direction", {}))
    return merged


def agree_count(fraction: float, n_edited: int) -> int:
    """Recover a cell's agreeing-subject count from its stored fraction.

    counterfactual.json stores sign agreement as a fraction of the edited
    subjects rather than as a count. The product is an exact integer for
    every banked cell; anything else means the fraction and ``n_edited``
    disagree about which subjects were scored, which would silently
    corrupt the interval, so it raises instead.
    """
    exact = fraction * n_edited
    count = round(exact)
    if abs(exact - count) > 1e-6:
        raise ValueError(
            f"sign agreement {fraction} over n={n_edited} is not a whole "
            f"number of subjects ({exact})"
        )
    return count


def render(results: dict[str, Any]) -> str:
    """Return the LaTeX tabular, one block per edit and one row per event."""
    lines = [
        "% GENERATED by scripts/make_counterfactual_table.py -- do not hand-edit.",
        "% Sign agreement in percent per horizon, with a Wilson 95% interval.",
        "% Arms with no expected direction (the lab-removal arm) are omitted:",
        "% they have no sign agreement to report.",
        "\\begin{tabular}{l" + "r" * len(HORIZONS) + "}",
        "\\toprule",
        "Event & " + " & ".join(f"{h[:-1]}\\,h" for h in HORIZONS) + " \\\\",
    ]
    for key, (name, change) in ARMS.items():
        arm = results["edits"].get(key)
        if arm is None:
            continue
        agreement = arm.get("sign_agreement") or {}
        if not agreement:
            continue
        n_edited = arm["n_edited"]
        expected = _expected(arm)
        lines += [
            "\\midrule",
            # \rlap keeps this wide spanning label from dumping its excess
            # width into the last horizon column and skewing the alignment.
            f"\\multicolumn{{{1 + len(HORIZONS)}}}{{l}}{{\\rlap{{\\emph{{{name}}}:"
            f" {change} ($n={n_edited}$ edited)}}}} \\\\",
        ]
        for event, per_horizon in sorted(agreement.items()):
            cells = []
            for horizon in HORIZONS:
                if horizon not in per_horizon:
                    cells.append("--")
                    continue
                fraction = per_horizon[horizon]
                lo, hi = wilson_interval(agree_count(fraction, n_edited), n_edited)
                cells.append(f"{fraction * 100:.0f} ({lo:.0f}--{hi:.0f})")
            label = EVENT_LABELS.get(event, event)
            if expected.get(event, 0) > 0:
                label += " $\\uparrow$"
            elif expected.get(event, 0) < 0:
                label += " $\\downarrow$"
            lines.append(f"{label} & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def main() -> None:
    """Write the counterfactual edit table from its results JSON."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("results_json", type=Path)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    results = json.loads(args.results_json.read_text())
    args.out.write_text(render(results))
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
