"""Render the input-level counterfactual edits as a LaTeX table with intervals.

paper/ml4h/tables/counterfactual.tex was previously hand-transcribed from
counterfactual.json despite carrying a "do not hand-edit" header, and it
reported bare percentages. Both are fixed here: every number is derived
from the JSON, and every cell carries a Wilson 95% interval.

The intervals matter more for this table than for any other in the paper.
Its arms are the smallest in the manuscript (40 and 44 edited subjects
against the comparator tables' hundreds of thousands of rows), it is the
source of the abstract's "85 to 98%", and the claim it supports is a
separation: the real edits against the inert control, which resets blood
pressure to its own normal value and should sit at chance. A separation
argued from four bare percentages at n=44 is not an argument; with
intervals it either holds or it does not.

Each (edit, event, horizon) cell is one binomial over edited subjects, so
Wilson applies directly. An interval on the 8/24/72 h average would need
the per-subject agreements, which counterfactual.json does not retain
(its ``per_subject`` lists are empty), the same limitation
scripts/make_edit_attribution_ci_table.py documents.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from scripts.make_edit_attribution_ci_table import wilson_interval


HORIZONS = ("8h", "24h", "72h")
TABLE_WIDTH = 0.78  # of \textwidth; see the tabular* comment in render()
EVENT_LABELS = {
    "death": "Death",
    "vasopressor_start": "Vasopressor",
    "icu_admission": "ICU adm.",
    "acute_kidney_injury": "AKI",
}
# Curated prose per arm: the display name and what the edit did. The
# expected DIRECTION is not curated, it is read out of the JSON's own
# expected_direction so the table cannot disagree with what was scored.
ARMS: dict[str, tuple[str, str]] = {
    "hypotension_6h": ("Induced hypotension", "SBP set to 80 mmHg over 6 h"),
    "normotension_6h": (
        "Inert control",
        "SBP set to its own normal value over 6 h",
    ),
    "creatinine_plus_1": ("Creatinine rise", "creatinine $+{v}$ {u}"),
    "creatinine_normal": (
        "Inert control",
        "creatinine set to a normal ${v}$ {u}",
    ),
    "lactate_x3": ("Lactate rise", "lactate $\\times 3$"),
}
#: Arms whose description carries an absolute value, so it must be
#: rendered in the unit the SOURCE reports in. GEMINI charts creatinine
#: in umol/L: printing "+1 mg/dL" over a table built from a +88.4 umol/L
#: edit would put this project's 2026-09-10 unit bug into the paper
#: rather than out of it. `{v}`/`{u}` in the description above are
#: filled from `ValueEdit.value_for` for the given source.
UNIT_SENSITIVE = ("creatinine_plus_1", "creatinine_normal")


def _describe(key: str, change: str, source: str) -> str:
    """Fill an arm's description with the value and unit ``source`` uses."""
    if "{v}" not in change:
        return change
    from odyssey.data.code_mapping import unit_for  # noqa: PLC0415
    from odyssey.inference.counterfactual import STANDARD_EDITS  # noqa: PLC0415

    edit = STANDARD_EDITS[key]
    prefixes = edit.prefixes(source)
    values = {edit.value_for(prefix, source) for prefix in prefixes}
    units = {unit_for(prefix, source=source) or "mg/dL" for prefix in prefixes}
    if len(values) != 1 or len(units) != 1:
        raise ValueError(
            f"arm {key!r} resolves to {sorted(values)} in {sorted(units)} on "
            f"{source!r}; one label cannot describe two units"
        )
    value = values.pop()
    return change.format(v=f"{value:g}", u=units.pop().replace("umol/L", "$\\mu$mol/L"))


def _expected(arm: dict[str, Any]) -> dict[str, int]:
    """Merge the expected_direction of every edit spec in one arm."""
    merged: dict[str, int] = {}
    for spec in arm.get("edits", []):
        merged.update(spec.get("expected_direction", {}))
    return merged


def agree_count(fraction: float, n_edited: int) -> int:
    """Recover a cell's agreeing-subject count from its stored fraction.

    counterfactual.json stores sign agreement as a fraction of the edited
    subjects rather than as a count. The product is an exact integer for
    every banked cell; anything else means the fraction and ``n_edited``
    disagree about which subjects were scored, which would silently
    corrupt the interval, so it raises instead.
    """
    exact = fraction * n_edited
    count = round(exact)
    if abs(exact - count) > 1e-6:
        raise ValueError(
            f"sign agreement {fraction} over n={n_edited} is not a whole "
            f"number of subjects ({exact})"
        )
    return count


def render(results: dict[str, Any], source: str = "mimic_iv") -> str:
    """Return the LaTeX tabular, one block per edit and one row per event."""
    lines = [
        "% GENERATED by scripts/make_counterfactual_table.py -- do not hand-edit.",
        "% Sign agreement in percent per horizon, with a Wilson 95% interval.",
        "% Arms with no expected direction (the lab-removal arm) are omitted:",
        "% they have no sign agreement to report.",
        # tabular* + extracolsep spreads the columns to a set width. A plain
        # tabular sizes to its numeric columns and leaves them crammed into
        # the left of a two-column-wide float; the full \textwidth flings
        # them to the margins instead. TABLE_WIDTH is the middle.
        # arraystretch gives the rows vertical air: at \scriptsize the
        # default leading packs the group headers against their own data.
        "\\renewcommand{\\arraystretch}{1.2}%",
        f"\\begin{{tabular*}}{{{TABLE_WIDTH}\\textwidth}}{{@{{\\extracolsep{{\\fill}}}}l"
        + "r" * len(HORIZONS)
        + "}",
        "\\toprule",
        "Event & " + " & ".join(f"{h[:-1]}\\,h" for h in HORIZONS) + " \\\\",
    ]
    for key, (name, template) in ARMS.items():
        change = _describe(key, template, source)
        arm = results["edits"].get(key)
        if arm is None:
            continue
        agreement = arm.get("sign_agreement") or {}
        if not agreement:
            continue
        n_edited = arm["n_edited"]
        expected = _expected(arm)
        lines += [
            "\\addlinespace[3pt]",
            "\\midrule",
            # \rlap so the label contributes no width: inside a fixed-width
            # tabular*, a wide spanning row otherwise dumps its excess into
            # the gap before the last column and unbalances the spacing.
            f"\\multicolumn{{{1 + len(HORIZONS)}}}{{@{{}}l}}{{\\rlap{{\\emph{{{name}}}:"
            f" {change} ($n={n_edited}$ edited)}}}} \\\\[2pt]",
        ]
        for event, per_horizon in sorted(agreement.items()):
            cells = []
            for horizon in HORIZONS:
                if horizon not in per_horizon:
                    cells.append("--")
                    continue
                fraction = per_horizon[horizon]
                lo, hi = wilson_interval(agree_count(fraction, n_edited), n_edited)
                cells.append(f"{fraction * 100:.0f} ({lo:.0f}--{hi:.0f})")
            label = EVENT_LABELS.get(event, event)
            if expected.get(event, 0) > 0:
                label += " $\\uparrow$"
            elif expected.get(event, 0) < 0:
                label += " $\\downarrow$"
            lines.append(f"{label} & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular*}"]
    return "\n".join(lines) + "\n"


def main() -> None:
    """Write the counterfactual edit table from its results JSON."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("results_json", type=Path)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument(
        "--source",
        default="mimic_iv",
        help=(
            "the source the run scored, so an absolute edit is labelled in "
            "the unit that source reports (GEMINI charts creatinine in "
            "umol/L, MIMIC-IV and eICU-CRD in mg/dL)"
        ),
    )
    args = parser.parse_args()

    results = json.loads(args.results_json.read_text())
    args.out.write_text(render(results, args.source))
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
