"""Render the automated occlusion+worsen-edit cohort validation as a LaTeX table.

Reads the JSON scripts/parse_edit_attribution_logs.py writes (one entry per
cohort_worsen.py run: concept, source, n, and one sign-agreement cell per
event/horizon) and emits one row per (concept, source), each event's three
horizons averaged into a single percentage. icu_admission on eICU-CRD is
degenerate for the same reason Appendix's comparator tables already exclude
it there (Section 5.4): most eICU held-out records carry exactly one
ICU_ADMISSION code, at the start of the stay, so the "future" hazard this
event measures is structurally non-recurring past that point -- its cell is
marked, not silently averaged in as if it meant the same thing as elsewhere.

Runs tagged ``selection: random`` (the random-code control, same subjects,
same number of codes, same edit machinery, codes drawn uniformly from the
same candidate pool) are left out by default so the published table does
not change; ``--with-random`` adds a "Codes" column and places each
random-arm row directly under its attributed row.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


CONCEPT_LABELS = {
    "sepsis3": "Sepsis-3",
    "qsofa": "qSOFA",
    "aki_stage_3": "AKI stage 3",
}
SOURCE_LABELS = {"mimic_iv": "MIMIC-IV", "eicu": "eICU-CRD"}
EVENTS = ("death", "vasopressor_start", "icu_admission", "acute_kidney_injury")
EVENT_LABELS = {
    "death": "Death",
    "vasopressor_start": "Vasopressor",
    "icu_admission": "ICU adm.",
    "acute_kidney_injury": "AKI",
}
# icu_admission's hazard is structurally non-recurring for most eICU
# subjects (see module docstring) -- its cell is marked degenerate there,
# the same treatment Section 5.4's comparator tables already give it.
DEGENERATE = {("icu_admission", "eicu")}


SELECTION_LABELS = {"attributed": "attributed", "random": "random"}


def _mean_pct(run: dict[str, Any], event: str) -> float | None:
    cells = [c["pct"] for c in run["cells"] if c["event"] == event]
    return sum(cells) / len(cells) if cells else None


def _selection(run: dict[str, Any]) -> str:
    return str(run.get("selection") or "attributed")


def _ordered_runs(
    runs: list[dict[str, Any]], *, with_random: bool
) -> list[dict[str, Any]]:
    """Attributed runs in file order, each followed by its random-arm twin(s).

    Without ``with_random`` only the attributed runs are kept, so a JSON
    that carries both arms renders the same table as one that carries the
    attributed arm alone.
    """
    attributed = [r for r in runs if _selection(r) == "attributed"]
    if not with_random:
        return attributed
    others = [r for r in runs if _selection(r) != "attributed"]
    ordered: list[dict[str, Any]] = []
    for run in attributed:
        ordered.append(run)
        ordered += [
            o
            for o in others
            if (o["concept"], o["source"]) == (run["concept"], run["source"])
        ]
    matched = {id(o) for o in ordered}
    ordered += [o for o in others if id(o) not in matched]
    return ordered


def render(results: dict[str, Any], *, with_random: bool = False) -> str:
    """Return the LaTeX tabular for one row per (concept, source) run.

    ``with_random`` adds a "Codes" column (attributed / random) and the
    random-arm rows; the default output has neither.
    """
    runs = _ordered_runs(results["runs"], with_random=with_random)
    head = "Concept & Dataset & "
    spec = "ll"
    if with_random:
        head += "Codes & "
        spec += "l"
    lines = [
        "% GENERATED by scripts/make_edit_attribution_table.py -- do not hand-edit.",
        "% Each event's cell averages sign agreement over the 8/24/72h horizons.",
        "% dag = icu_admission on eICU-CRD, structurally non-recurring there (see caption).",
    ]
    if with_random:
        lines.append(
            "% random = same subjects and code count, codes drawn uniformly from the same window pool."
        )
    lines += [
        "\\begin{tabular}{" + spec + "r" + "r" * len(EVENTS) + "}",
        "\\toprule",
        head + "$n$ & " + " & ".join(EVENT_LABELS[e] for e in EVENTS) + " \\\\",
        "\\midrule",
    ]
    for run in runs:
        concept = CONCEPT_LABELS.get(run["concept"], run["concept"])
        source = SOURCE_LABELS.get(run["source"], run["source"])
        cells = []
        for event in EVENTS:
            if (event, run["source"]) in DEGENERATE:
                cells.append("--$^\\dagger$")
                continue
            mean_pct = _mean_pct(run, event)
            cells.append(f"{mean_pct:.0f}\\%" if mean_pct is not None else "--")
        row = f"{concept} & {source} & "
        if with_random:
            sel = _selection(run)
            row += SELECTION_LABELS.get(sel, sel) + " & "
        lines.append(row + f"{run['n_subjects']} & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def main() -> None:
    """Write the automated edit-attribution table from its results JSON."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("results_json", type=Path)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument(
        "--with-random",
        action="store_true",
        help="add the random-code control rows and a Codes column",
    )
    args = parser.parse_args()

    results = json.loads(args.results_json.read_text())
    args.out.write_text(render(results, with_random=args.with_random))
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
