"""Per-concept readout AUROC across the three databases, from banked evals.

Appendix C carried a mixture-vs-decomposed scatter plot that stopped
meaning anything when the decomposed series left this paper, and was
removed without a replacement, leaving the section empty. This is the
replacement the TODO asked for: which concepts read out strongest and
weakest, on every database that supervises them.

One row per concept in the registry's order, one column per database,
"--" where a run did not supervise that concept. The three runs
supervise different counts (29 on MIMIC-IV, 26 on eICU-CRD, 15 on
GEMINI), which is the point of showing them side by side rather than
averaging.

Concepts can be EXCLUDED per database with ``--exclude``. That is not a
cosmetic option: `gemini_full_v10_15c` predates the per-unit LOINC fix
of PR #221, so its `aki_stage_3` was supervised against a threshold
compared in the wrong unit and its AUROC measures a known-fixed label
bug rather than the model. An excluded cell prints a dagger, so the
table shows the gap instead of hiding it.

Usage::

    uv run python scripts/make_readout_table.py \
        research_journal/figure_data/vm1/full_run_v10/inference_results.json MIMIC-IV \
        research_journal/figure_data/vm2/eicu_full_v10/inference_results.json eICU-CRD \
        research_journal/figure_data/gemini/gemini_full_v10_15c/\
            inference_results.json GEMINI \
        --exclude GEMINI:aki_stage_3 \
        --output paper/ml4h/tables/readout.tex
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path
from typing import Any

from odyssey.data.concepts import canonical_concept_name


logger = logging.getLogger(__name__)

#: Display names for concepts whose registry name understates a threshold.
_DISPLAY = {
    "sustained_hypotension_map": "sustained hypotension (MAP)",
    "anemia": "severe anemia",
    "hypokalemia": "severe hypokalemia",
}


def _display(name: str) -> str:
    canon = canonical_concept_name(name)
    return _DISPLAY.get(canon, canon.replace("_", " "))


def _readouts(path: Path) -> dict[str, float]:
    """Concept -> AUROC for one run, keyed by canonical name."""
    metrics = json.loads(path.read_text())["concept_metrics"]
    return {canonical_concept_name(m["name"]): m["auroc"] for m in metrics}


def render(
    runs: list[tuple[str, dict[str, float]]],
    excluded: dict[str, set[str]],
) -> str:
    """One row per concept, one column per database."""
    order: list[str] = []
    for _, readouts in runs:
        for name in readouts:
            if name not in order:
                order.append(name)

    lines = [
        "% GENERATED by scripts/make_readout_table.py -- do not hand-edit.",
        "% Held-out concept AUROC at visit ends. '--': not supervised by that",
        "% run. '$\\dagger$': excluded, see the caption.",
        "\\begin{tabular}{@{}l" + "r" * len(runs) + "@{}}",
        "\\toprule",
        "Concept & " + " & ".join(label for label, _ in runs) + " \\\\",
        "\\midrule",
    ]
    for name in sorted(order, key=_display):
        cells = []
        for label, readouts in runs:
            if name in excluded.get(label, set()):
                cells.append("$\\dagger$")
            elif name in readouts:
                cells.append(f"{readouts[name]:.3f}")
            else:
                cells.append("--")
        lines.append(f"{_display(name)} & " + " & ".join(cells) + " \\\\")

    lines.append("\\midrule")
    medians = []
    for label, readouts in runs:
        scored = sorted(
            v for k, v in readouts.items() if k not in excluded.get(label, set())
        )
        medians.append(f"{scored[len(scored) // 2]:.3f}" if scored else "--")
    lines.append("\\emph{median} & " + " & ".join(medians) + " \\\\")
    counts = []
    for label, readouts in runs:
        n = len([k for k in readouts if k not in excluded.get(label, set())])
        counts.append(str(n))
    lines.append("\\emph{concepts scored} & " + " & ".join(counts) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def _parse_exclusions(specs: list[str]) -> dict[str, set[str]]:
    out: dict[str, set[str]] = {}
    for spec in specs:
        if ":" not in spec:
            raise SystemExit(f"--exclude wants LABEL:concept, got {spec!r}")
        label, concept = spec.split(":", 1)
        out.setdefault(label, set()).add(canonical_concept_name(concept))
    return out


def main() -> None:
    """Write the per-concept readout table."""
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("pairs", nargs="+", help="alternating results JSON and label")
    parser.add_argument("--exclude", action="append", default=[])
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    if len(args.pairs) % 2:
        raise SystemExit("pairs must alternate path and label")
    runs: list[tuple[str, dict[str, float]]] = []
    for path, label in zip(args.pairs[::2], args.pairs[1::2], strict=True):
        runs.append((label, _readouts(Path(path))))

    excluded = _parse_exclusions(args.exclude)
    for label in excluded:
        if label not in {lbl for lbl, _ in runs}:
            raise SystemExit(f"--exclude names {label!r}, which is not a column")

    args.output.write_text(render(runs, excluded))
    total: Any = sum(len(r) for _, r in runs)
    logger.info("wrote %s (%d cells)", args.output, total)
    print(f"wrote {args.output}")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    main()
