"""Turn steering-benchmark JSON into the paper's dial table.

One row per concept and direction; one column per declared outcome at the
chosen horizon, showing the steered-over-unsteered risk ratio, bold when
the paired subject-clustered delta separates from zero and has the
clinically expected sign, and marked with a dagger when it separates the
WRONG way. A second JSON (``--after``) adds a matching block so a
steering-trained model can sit beside its untrained parent on the same
shard and dials.

Usage::

    uv run python scripts/make_steering_table.py \\
        --before figure_data/vm1/full_run_DEC_v12/steering_smoke_v2.json \\
        --after figure_data/vm1/full_run_DEC_v12_steer/steering_smoke.json \\
        --output-tex paper/ml4h/tables/steering_dials.tex
"""

from __future__ import annotations

import argparse
import json
import logging
import math
from pathlib import Path
from typing import Any

from odyssey.data.concepts import canonical_concept_name


logger = logging.getLogger(__name__)

EVENT_LABELS = {
    "vasopressor_start": "Pressors",
    "icu_admission": "ICU",
    "acute_kidney_injury": "AKI",
    "death": "Death",
    "sepsis3": "Sepsis-3",
    "readmission_30d": "Readmit",
}


def _cell(outcome: dict[str, Any]) -> str:
    """One risk ratio, bold if separated as expected, dagger if separated wrong."""
    ratio = outcome["relative_change"]
    if math.isnan(ratio):  # never at risk of this event
        return "--"
    text = f"{ratio:.2f}"
    if outcome.get("expected_sign") is None:
        return text
    if outcome["separated"] and outcome["as_expected"]:
        return f"\\textbf{{{text}}}"
    if outcome["separated"] and not outcome["as_expected"]:
        return f"{text}$^\\dagger$"
    return text


def rows_for(
    payload: dict[str, Any], *, horizon: float
) -> list[tuple[str, str, str, list[str]]]:
    """``(concept, direction, respond, cells)`` per summary at ``horizon``."""
    events = [e for e in payload["event_names"] if e in EVENT_LABELS]
    out = []
    for s in payload["summaries"]:
        by_event = {(o["event"], o["horizon_hours"]): o for o in s["outcomes"]}
        cells = []
        for e in events:
            o = by_event.get((e, horizon))
            if o is None:
                cells.append("\\textcolor{gray}{--}")
            elif o.get("expected_sign") is None:
                cells.append(f"\\textcolor{{gray}}{{{o['relative_change']:.2f}}}")
            else:
                cells.append(_cell(o))
        respond = f"{s['respond_baseline']:.2f}$\\to${s['respond_steered']:.2f}"
        arrow = "$\\uparrow$" if s["direction"] == "amplify" else "$\\downarrow$"
        name = canonical_concept_name(s["concept"]).replace("_", " ")
        out.append((name, arrow, respond, cells))
    return out


def render(
    before: dict[str, Any], after: dict[str, Any] | None, *, horizon: float
) -> str:
    """Render the tabular body with a header comment recording provenance."""
    events = [e for e in before["event_names"] if e in EVENT_LABELS]
    cols = "ll" + "l" + "r" * len(events)
    head = (
        " & ".join(["Dial", "", "$k_c$", *[EVENT_LABELS[e] for e in events]]) + " \\\\"
    )
    lines = [
        "% GENERATED by scripts/make_steering_table.py -- do not hand-edit.",
        f"% site: {before.get('site')} layer {before.get('layer_index')} tau {before.get('tau')}; horizon {horizon:g}h",
        "% bold: paired delta separates from zero in the clinically expected direction;",
        "% dagger: separates the wrong way; gray: no expectation declared for that dial.",
        f"\\begin{{tabular}}{{{cols}}}",
        "\\toprule",
        head,
        "\\midrule",
    ]
    blocks = [("before steering training", before)]
    if after is not None:
        blocks.append(("after steering training", after))
    for label, payload in blocks:
        if after is not None:
            lines.append(
                f"\\multicolumn{{{3 + len(events)}}}{{l}}{{\\emph{{{label}}}}} \\\\"
            )
        for concept, arrow, respond, cells in rows_for(payload, horizon=horizon):
            lines.append(" & ".join([concept, arrow, respond, *cells]) + " \\\\")
        if after is not None and label.startswith("before"):
            lines.append("\\midrule")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def main() -> None:
    """Write the dial table."""
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--before", required=True, type=Path)
    parser.add_argument("--after", type=Path, default=None)
    parser.add_argument("--horizon", type=float, default=24.0)
    parser.add_argument("--output-tex", required=True, type=Path)
    args = parser.parse_args()
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s"
    )
    before = json.loads(args.before.read_text())
    after = json.loads(args.after.read_text()) if args.after else None
    if after is not None and after["event_names"] != before["event_names"]:
        raise SystemExit(
            "before/after files score different event heads; refusing to align columns"
        )
    args.output_tex.write_text(render(before, after, horizon=args.horizon))
    logger.info(
        "wrote %s (%d dial rows)",
        args.output_tex,
        len(before["summaries"]) + (len(after["summaries"]) if after else 0),
    )


if __name__ == "__main__":
    main()
