"""Render per-horizon sign agreement with Wilson intervals as a LaTeX table.

scripts/make_edit_attribution_table.py collapses each event's three
horizons into one percentage, which is the number the body reports. That
average carries no interval: the 8/24/72 h cells are scored on the same
50 subjects, so they are correlated, and a valid interval on their mean
needs the per-subject agreements that cohort_worsen.py's logs do not
retain. What the logs DO retain is each cell's agree/total, and a single
cell is a plain binomial over subjects. This table therefore reports the
three horizons separately, each with a Wilson 95% interval, so the
reader can see the uncertainty at n=50 without the paper claiming an
interval it cannot compute.

Wilson rather than the normal approximation because several cells sit at
or beside 50/50, where the normal interval degenerates to zero width.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any


CONCEPT_LABELS = {
    "sepsis3": "Sepsis-3",
    "qsofa": "qSOFA",
    "aki_stage_3": "AKI stage 3",
}
SOURCE_LABELS = {"mimic_iv": "MIMIC-IV", "eicu": "eICU-CRD"}
EVENTS = ("death", "vasopressor_start", "icu_admission", "acute_kidney_injury")
EVENT_LABELS = {
    "death": "Death",
    "vasopressor_start": "Vasopressor",
    "icu_admission": "ICU adm.",
    "acute_kidney_injury": "AKI",
}
HORIZONS = ("8h", "24h", "72h")
# Reported here for completeness, marked, and excluded from the body's
# headline on the structural grounds Section 5.4 gives: most eICU-CRD
# held-out records carry exactly one ICU_ADMISSION code, at the start of
# the stay, so that hazard is non-recurring past the index time.
DEGENERATE = {("icu_admission", "eicu")}
Z95 = 1.959964


def wilson_interval(agree: int, total: int, z: float = Z95) -> tuple[float, float]:
    """Return the Wilson score interval for ``agree``/``total``, in percent.

    Raises ``ValueError`` on a non-positive denominator rather than
    dividing by zero: a cell with no scored subjects is a parsing bug
    upstream, not a wide interval.
    """
    if total <= 0:
        raise ValueError(f"cannot interval a cell with total={total}")
    p = agree / total
    denom = 1.0 + z * z / total
    center = p + z * z / (2 * total)
    halfwidth = z * math.sqrt(p * (1.0 - p) / total + z * z / (4.0 * total * total))
    lo = max(0.0, (center - halfwidth) / denom)
    hi = min(1.0, (center + halfwidth) / denom)
    return lo * 100.0, hi * 100.0


def _cell(run: dict[str, Any], event: str, horizon: str) -> str:
    match = [c for c in run["cells"] if c["event"] == event and c["horizon"] == horizon]
    if not match:
        return "--"
    cell = match[0]
    lo, hi = wilson_interval(cell["agree"], cell["total"])
    return f"{cell['pct']:.0f} ({lo:.0f}--{hi:.0f})"


def render(results: dict[str, Any]) -> str:
    """Return the LaTeX tabular, one block per run and one row per event."""
    lines = [
        "% GENERATED by scripts/make_edit_attribution_ci_table.py -- do not hand-edit.",
        "% Per-horizon sign agreement, percent, with a Wilson 95% interval.",
        "% dag = icu_admission on eICU-CRD, degenerate there (see caption).",
        "\\begin{tabular}{l" + "r" * len(HORIZONS) + "}",
        "\\toprule",
        "Event & " + " & ".join(f"{h[:-1]}\\,h" for h in HORIZONS) + " \\\\",
    ]
    for run in results["runs"]:
        concept = CONCEPT_LABELS.get(run["concept"], run["concept"])
        source = SOURCE_LABELS.get(run["source"], run["source"])
        lines += [
            "\\midrule",
            f"\\multicolumn{{{1 + len(HORIZONS)}}}{{l}}{{\\emph{{{concept}, {source}}}"
            f" ($n={run['n_subjects']}$)}} \\\\",
        ]
        for event in EVENTS:
            label = EVENT_LABELS.get(event, event)
            if (event, run["source"]) in DEGENERATE:
                label += "$^\\dagger$"
            cells = [_cell(run, event, h) for h in HORIZONS]
            lines.append(f"{label} & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def main() -> None:
    """Write the per-horizon interval table from the cohort results JSON."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("results_json", type=Path)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    results = json.loads(args.results_json.read_text())
    args.out.write_text(render(results))
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
