"""Turn a concept atlas JSON into two LaTeX tables for the paper.

``--unknown``: the most active unnamed concepts with the events one unit of
each promotes, so a reader can judge what the model invented. ``--known``:
every named concept with its top promoted events (Steerling's Known Concept
Alignment), the sanity check that a dial promotes what its name says.

Usage::

    uv run python scripts/make_atlas_table.py \\
        --atlas figure_data/vm1/full_run_DEC_v12/concept_atlas.json \\
        --unknown tables/unknown_atlas.tex --known tables/known_alignment.tex
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

from odyssey.data.concepts import canonical_concept_name


_STRIP = [
    (r" \[Mass/volume\] in Serum or Plasma", ""),
    (r" \[Moles/volume\] in Serum or Plasma", ""),
    (r" \[Mass/volume\] in Blood", ""),
    (r" \[#/volume\] in Blood by Automated count", ""),
    (r" in Blood by Automated count", ""),
    (r" by Automated count", ""),
    (r"^MEDICATION//", ""),
    (r"//Administered$", ""),
    (r"^(START|STOP)//", r"\1 "),
    (r"^HOSPITAL_ADMISSION//", "admission: "),
]


def short_name(name: str, limit: int = 34) -> str:
    """Shorten a MEDS description for a table cell, escaping LaTeX specials."""
    for pat, rep in _STRIP:
        name = re.sub(pat, rep, name)
    name = name.strip()
    if len(name) > limit:
        # Cut at a word boundary so a cell never ends mid-word.
        cut = name[: limit - 1]
        if " " in cut[limit // 2 :]:
            cut = cut[: cut.rfind(" ")]
        name = cut.rstrip() + "…"
    return (
        name.replace("&", "\\&")
        .replace("%", "\\%")
        .replace("_", "\\_")
        .replace("#", "\\#")
    )


def unknown_table(atlas: dict[str, Any], *, top_concepts: int, top_events: int) -> str:
    """Rows: the most active unnamed concepts and what each promotes."""
    lines = [
        "% GENERATED by scripts/make_atlas_table.py -- do not hand-edit.",
        f"% source: {atlas.get('run_dir')} ({atlas.get('n_positions')} positions)",
        "\\begin{tabular}{lrp{0.72\\linewidth}}",
        "\\toprule",
        "Unnamed concept & mean $u_j$ & events one unit of it promotes most \\\\",
        "\\midrule",
    ]
    for row in atlas["unknown"][:top_concepts]:
        events = ", ".join(short_name(p["name"]) for p in row["promotes"][:top_events])
        lines.append(
            f"{canonical_concept_name(row['name']).replace('_', ' ')} & {row['mean_activation']:.2f} & {events} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def cross_table(
    atlases: list[tuple[str, dict[str, Any]]], *, top_concepts: int, top_events: int
) -> str:
    """Rows: the most active unnamed concepts of each database side by side.

    One block per database (label, atlas), the ``top_concepts`` most
    active unnamed slots each, so a reader can compare what the models
    invented for themselves on different care settings and code systems.
    """
    lines = [
        "% GENERATED by scripts/make_atlas_table.py -- do not hand-edit.",
        "% sources: "
        + "; ".join(f"{label}: {a.get('run_dir')}" for label, a in atlases),
        "\\begin{tabular}{llrp{0.62\\linewidth}}",
        "\\toprule",
        "Database & slot & mean $u_j$ & events one unit of it promotes most \\\\",
        "\\midrule",
    ]
    for label, atlas in atlases:
        for row in atlas["unknown"][:top_concepts]:
            events = ", ".join(
                short_name(p["name"]) for p in row["promotes"][:top_events]
            )
            slot = canonical_concept_name(row["name"]).replace("unknown_", "")
            lines.append(
                f"{label} & {slot} & {row['mean_activation']:.2f} & {events} \\\\"
            )
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def known_table(atlas: dict[str, Any], *, top_events: int) -> str:
    """Rows: every named concept with its top promoted events."""
    lines = [
        "% GENERATED by scripts/make_atlas_table.py -- do not hand-edit.",
        f"% source: {atlas.get('run_dir')} ({atlas.get('n_positions')} positions)",
        "\\begin{tabular}{lrrp{0.60\\linewidth}}",
        "\\toprule",
        "Concept & $\\|K_c\\|$ & mean $k_c$ & events one unit of it promotes most \\\\",
        "\\midrule",
    ]
    for row in atlas["known"]:
        events = ", ".join(short_name(p["name"]) for p in row["promotes"][:top_events])
        lines.append(
            f"{canonical_concept_name(row['name']).replace('_', ' ')} & {row['norm']:.2f} & {row['mean_activation']:.2f} & {events} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def main() -> None:
    """Write the requested tables."""
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--atlas", required=True, type=Path)
    parser.add_argument("--unknown", type=Path, default=None)
    parser.add_argument("--known", type=Path, default=None)
    parser.add_argument("--top-concepts", type=int, default=10)
    parser.add_argument("--top-events", type=int, default=5)
    parser.add_argument(
        "--cross",
        nargs="*",
        default=None,
        metavar="LABEL=ATLAS_JSON",
        help="extra atlases for a cross-database table of the most active unnamed slots",
    )
    parser.add_argument("--cross-out", type=Path, default=None)
    parser.add_argument("--cross-top", type=int, default=2)
    args = parser.parse_args()
    atlas = json.loads(args.atlas.read_text())
    share = atlas["contribution_share"]
    print(
        f"contribution shares: named {share['named']:.3f}, unknown {share['unknown']:.3f}, residual {share['residual']:.3f}"
    )
    if args.unknown:
        args.unknown.write_text(
            unknown_table(
                atlas, top_concepts=args.top_concepts, top_events=args.top_events
            )
        )
        print(f"wrote {args.unknown}")
    if args.known:
        args.known.write_text(known_table(atlas, top_events=args.top_events))
        print(f"wrote {args.known}")
    if args.cross_out:
        atlases = (
            [(args.atlas_label, atlas)] if getattr(args, "atlas_label", None) else []
        )
        for spec in args.cross or []:
            label, _, path = spec.partition("=")
            atlases.append((label, json.loads(Path(path).read_text())))
        args.cross_out.write_text(
            cross_table(
                atlases, top_concepts=args.cross_top, top_events=args.top_events
            )
        )
        print(f"wrote {args.cross_out}")


if __name__ == "__main__":
    main()
