"""Render the automated occlusion+worsen-edit cohort validation as a LaTeX table.

Reads the JSON scripts/parse_edit_attribution_logs.py writes (one entry per
cohort_worsen.py run: concept, source, n, and one sign-agreement cell per
event/horizon) and emits one row per (concept, source), each event's three
horizons averaged into a single percentage. icu_admission on eICU-CRD is
degenerate for the same reason Appendix's comparator tables already exclude
it there (Section 5.4): most eICU held-out records carry exactly one
ICU_ADMISSION code, at the start of the stay, so the "future" hazard this
event measures is structurally non-recurring past that point -- its cell is
marked, not silently averaged in as if it meant the same thing as elsewhere.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


CONCEPT_LABELS = {
    "sepsis3": "Sepsis-3",
    "qsofa": "qSOFA",
    "aki_stage_3": "AKI stage 3",
}
SOURCE_LABELS = {"mimic_iv": "MIMIC-IV", "eicu": "eICU-CRD"}
EVENTS = ("death", "vasopressor_start", "icu_admission", "acute_kidney_injury")
EVENT_LABELS = {
    "death": "Death",
    "vasopressor_start": "Vasopressor",
    "icu_admission": "ICU adm.",
    "acute_kidney_injury": "AKI",
}
# icu_admission's hazard is structurally non-recurring for most eICU
# subjects (see module docstring) -- its cell is marked degenerate there,
# the same treatment Section 5.4's comparator tables already give it.
DEGENERATE = {("icu_admission", "eicu")}


def _mean_pct(run: dict[str, Any], event: str) -> float | None:
    cells = [c["pct"] for c in run["cells"] if c["event"] == event]
    return sum(cells) / len(cells) if cells else None


def render(results: dict[str, Any]) -> str:
    """Return the LaTeX tabular for one row per (concept, source) run."""
    lines = [
        "% GENERATED by scripts/make_edit_attribution_table.py -- do not hand-edit.",
        "% Each event's cell averages sign agreement over the 8/24/72h horizons.",
        "% dag = icu_admission on eICU-CRD, structurally non-recurring there (see caption).",
        "\\begin{tabular}{llr" + "r" * len(EVENTS) + "}",
        "\\toprule",
        "Concept & Dataset & $n$ & "
        + " & ".join(EVENT_LABELS[e] for e in EVENTS)
        + " \\\\",
        "\\midrule",
    ]
    for run in results["runs"]:
        concept = CONCEPT_LABELS.get(run["concept"], run["concept"])
        source = SOURCE_LABELS.get(run["source"], run["source"])
        cells = []
        for event in EVENTS:
            if (event, run["source"]) in DEGENERATE:
                cells.append("--$^\\dagger$")
                continue
            mean_pct = _mean_pct(run, event)
            cells.append(f"{mean_pct:.0f}\\%" if mean_pct is not None else "--")
        lines.append(
            f"{concept} & {source} & {run['n_subjects']} & " + " & ".join(cells) + " \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def main() -> None:
    """Write the automated edit-attribution table from its results JSON."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("results_json", type=Path)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    results = json.loads(args.results_json.read_text())
    args.out.write_text(render(results))
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
