"""Render the eICU patient-overlap table from the banked patient_overlap_check.json.

Per event and horizon: hazard-head and GBM AUROC on held-out stays whose
patient also has a training-set stay ("overlap") and on the rest
("clean"), with the paired hazard-minus-GBM difference in each stratum.

Usage::

    python scripts/make_overlap_table.py <patient_overlap_check.json> \
        --arm decomposed_v13 --output paper/ml4h/tables/eicu_overlap.tex
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


EVENT_ORDER = ("death", "vasopressor_start", "acute_kidney_injury", "icu_admission")
EVENT_NAMES = {
    "death": "Death",
    "vasopressor_start": "Vasopressor",
    "acute_kidney_injury": "AKI",
    "icu_admission": "ICU adm.",
}


def render(cells: dict[str, dict[str, Any]], arm: str = "") -> str:
    """Return the LaTeX tabular for one arm's per-cell overlap results.

    The arm is stamped into the output. This file used to carry no
    provenance at all, and the paper shipped the decomposed arm's numbers
    in a mixture-model paper for weeks because nothing in the generated
    .tex said which arm produced it (found 2026-09-09). A header comment
    makes the next such drift visible on inspection.
    """
    lines = [
        f"% GENERATED by scripts/make_overlap_table.py --arm {arm} -- do not hand-edit.",
        "\\begin{tabular}{@{}llrrrlrrrl@{}}",
        "\\toprule",
        "& & \\multicolumn{4}{c}{patient also in training} & \\multicolumn{4}{c}{patient not in training} \\\\",
        "\\cmidrule(lr){3-6}\\cmidrule(lr){7-10}",
        "Event & $h$ & $n$ & hazard & GBM & $\\Delta$ [95\\% CI] & $n$ & hazard & GBM & $\\Delta$ [95\\% CI] \\\\",
        "\\midrule",
    ]
    for event in EVENT_ORDER:
        first = True
        for h in ("8h", "24h", "72h"):
            c = cells.get(f"{event}@{h}")
            if not c or "overlap" not in c or "clean" not in c:
                continue
            row = [EVENT_NAMES[event] if first else "", h[:-1]]
            for strat in ("overlap", "clean"):
                s = c[strat]
                row += [
                    f"{s['n']:,}",
                    f"{s['hazard']:.3f}",
                    f"{s['gbm']:.3f}",
                    f"{s['hazard_minus_gbm'][0]:+.3f} [{s['hazard_minus_gbm'][1]:+.3f}, {s['hazard_minus_gbm'][2]:+.3f}]",
                ]
            lines.append(" & ".join(row) + " \\\\")
            first = False
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def main() -> None:
    """Parse arguments and write the table."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("result", type=Path)
    parser.add_argument("--arm", required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    payload = json.loads(args.result.read_text())
    args.output.write_text(render(payload[args.arm], arm=args.arm))
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
