"""Turn a concept atlas JSON into two LaTeX tables for the paper.

``--unknown``: the most active unnamed concepts with the events one unit of
each promotes, so a reader can judge what the model invented. ``--known``:
every named concept with its top promoted events (Steerling's Known Concept
Alignment), the sanity check that a dial promotes what its name says.

Usage::

    uv run python scripts/make_atlas_table.py \\
        --atlas figure_data/vm1/full_run_DEC_v12/concept_atlas.json \\
        --unknown tables/unknown_atlas.tex --known tables/known_alignment.tex
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


_STRIP = [
    (r" \[Mass/volume\] in Serum or Plasma", ""),
    (r" \[Moles/volume\] in Serum or Plasma", ""),
    (r" \[Mass/volume\] in Blood", ""),
    (r" \[#/volume\] in Blood by Automated count", ""),
    (r" in Blood by Automated count", ""),
    (r" by Automated count", ""),
    (r"^MEDICATION//", ""),
    (r"//Administered$", ""),
    (r"^(START|STOP)//", r"\1 "),
    (r"^HOSPITAL_ADMISSION//", "admission: "),
]


def short_name(name: str, limit: int = 34) -> str:
    """Shorten a MEDS description for a table cell, escaping LaTeX specials."""
    for pat, rep in _STRIP:
        name = re.sub(pat, rep, name)
    name = name.strip()
    if len(name) > limit:
        name = name[: limit - 1].rstrip() + "…"
    return (
        name.replace("&", "\\&")
        .replace("%", "\\%")
        .replace("_", "\\_")
        .replace("#", "\\#")
    )


def unknown_table(atlas: dict[str, Any], *, top_concepts: int, top_events: int) -> str:
    """Rows: the most active unnamed concepts and what each promotes."""
    lines = [
        "% GENERATED by scripts/make_atlas_table.py -- do not hand-edit.",
        f"% source: {atlas.get('run_dir')} ({atlas.get('n_positions')} positions)",
        "\\begin{tabular}{lrp{0.72\\linewidth}}",
        "\\toprule",
        "Unnamed concept & mean $u_j$ & events one unit of it promotes most \\\\",
        "\\midrule",
    ]
    for row in atlas["unknown"][:top_concepts]:
        events = ", ".join(short_name(p["name"]) for p in row["promotes"][:top_events])
        lines.append(
            f"{row['name'].replace('_', ' ')} & {row['mean_activation']:.2f} & {events} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def known_table(atlas: dict[str, Any], *, top_events: int) -> str:
    """Rows: every named concept with its top promoted events."""
    lines = [
        "% GENERATED by scripts/make_atlas_table.py -- do not hand-edit.",
        f"% source: {atlas.get('run_dir')} ({atlas.get('n_positions')} positions)",
        "\\begin{tabular}{lrrp{0.60\\linewidth}}",
        "\\toprule",
        "Concept & $\\|K_c\\|$ & mean $k_c$ & events one unit of it promotes most \\\\",
        "\\midrule",
    ]
    for row in atlas["known"]:
        events = ", ".join(short_name(p["name"]) for p in row["promotes"][:top_events])
        lines.append(
            f"{row['name'].replace('_', ' ')} & {row['norm']:.2f} & {row['mean_activation']:.2f} & {events} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def main() -> None:
    """Write the requested tables."""
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--atlas", required=True, type=Path)
    parser.add_argument("--unknown", type=Path, default=None)
    parser.add_argument("--known", type=Path, default=None)
    parser.add_argument("--top-concepts", type=int, default=10)
    parser.add_argument("--top-events", type=int, default=5)
    args = parser.parse_args()
    atlas = json.loads(args.atlas.read_text())
    share = atlas["contribution_share"]
    print(
        f"contribution shares: named {share['named']:.3f}, unknown {share['unknown']:.3f}, residual {share['residual']:.3f}"
    )
    if args.unknown:
        args.unknown.write_text(
            unknown_table(
                atlas, top_concepts=args.top_concepts, top_events=args.top_events
            )
        )
        print(f"wrote {args.unknown}")
    if args.known:
        args.known.write_text(known_table(atlas, top_events=args.top_events))
        print(f"wrote {args.known}")


if __name__ == "__main__":
    main()
