"""The two-sided steering table: rows per dial, a totals block, a control line."""

import json
import runpy
from pathlib import Path

from odyssey.inference.specificity import score_run


SCRIPT = Path(__file__).resolve().parents[2] / "scripts" / "make_specificity_table.py"


def _delta(point: float) -> dict:
    return {"point": point, "ci_low": point - 0.01, "ci_high": point + 0.01, "n": 8}


def _summary(concept: str, direction: str, own: float, good_ratio: float) -> dict:
    flip = 1 if direction == "amplify" else -1
    return {
        "concept": concept,
        "direction": direction,
        "concept_shifts": [
            {
                "concept": concept,
                "baseline": 0.3,
                "steered": 0.3 + own,
                "delta": _delta(own),
                "expected_sign": flip,
                "as_expected": own * flip > 0,
                "separated": True,
            },
            {
                "concept": "hypertension",
                "baseline": 0.3,
                "steered": 0.29,
                "delta": _delta(-0.01 * flip),
                "expected_sign": -flip,
                "as_expected": True,
                "separated": True,
            },
            {
                "concept": "fever",
                "baseline": 0.3,
                "steered": 0.3,
                "delta": _delta(0.0),
                "expected_sign": None,
                "as_expected": None,
                "separated": False,
            },
        ],
        "outcomes": [
            {
                "event": "death",
                "horizon_hours": 24.0,
                "relative_change": 1.2 if flip > 0 else 0.9,
                "expected_sign": flip,
                "as_expected": True,
                "separated": True,
            },
            {
                "event": "icu_discharge",
                "horizon_hours": 24.0,
                "relative_change": good_ratio,
                "expected_sign": -flip,
                "as_expected": (good_ratio - 1) * (-flip) > 0,
                "separated": True,
            },
        ],
    }


def _write(path: Path, summaries: list[dict]) -> None:
    path.write_text(json.dumps({"summaries": summaries}))


def test_script_writes_a_tabular_with_dial_rows_and_totals(tmp_path: Path) -> None:
    dials = tmp_path / "dials.json"
    control = tmp_path / "control.json"
    _write(
        dials,
        [
            _summary("hypotension", "amplify", 0.10, 0.8),  # both-sided
            _summary("hypotension", "suppress", -0.08, 1.1),  # both-sided
        ],
    )
    _write(control, [_summary("hypotension", "amplify", 0.01, 1.2)])  # good went up
    out = tmp_path / "specificity.tex"
    module = runpy.run_path(str(SCRIPT), run_name="_not_main_")
    module["main"](
        [
            "--dials",
            str(dials),
            "--control",
            str(control),
            "--output-tex",
            str(out),
        ]
    )
    tex = out.read_text()
    assert tex.startswith("% GENERATED by scripts/make_specificity_table.py")
    assert "\\begin{tabular}{lrrrrrr}" in tex and tex.rstrip().endswith(
        "\\end{tabular}"
    )
    rows = [line for line in tex.splitlines() if line.endswith("\\\\")]
    # header, two dial rows, two totals rows
    assert len(rows) == 5
    assert rows[1].startswith("hypotension $\\uparrow$ & +0.10 &")
    assert rows[2].startswith("hypotension $\\downarrow$ & -0.08 &")
    assert "\\emph{concept dials} (2 dials)" in rows[3]
    assert "(2 both-sided)" in rows[3]
    assert "\\emph{random direction} (1 dials)" in rows[4]
    assert "0/1" in rows[4]  # the control's good outcome went the wrong way
    # the same scoring the paper's numbers come from
    scored = score_run(json.loads(dials.read_text())["summaries"])
    assert all(d.good_as_expected == 1 for d in scored)


def test_script_runs_without_a_control(tmp_path: Path) -> None:
    dials = tmp_path / "dials.json"
    _write(dials, [_summary("anemia", "amplify", 0.05, 0.95)])
    out = tmp_path / "t.tex"
    module = runpy.run_path(str(SCRIPT), run_name="_not_main_")
    module["main"](["--dials", str(dials), "--output-tex", str(out)])
    tex = out.read_text()
    assert "random direction" not in tex
    assert "severe anemia $\\uparrow$" in tex
